# Generated by Django 5.2.4 on 2025-07-22 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurvivalPlan', '0002_remove_survivalplan_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitem',
            name='Plan',
        ),
        migrations.AddField(
            model_name='planitem',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='SurvivalPlan.survivalplan'),
            preserve_default=False,
        ),
    ]
