# Generated by Django 5.2.4 on 2025-07-22 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SurvivalPlan', '0003_remove_planitem_plan_planitem_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('plans', models.ManyToManyField(blank=True, related_name='goals', to='SurvivalPlan.survivalplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
